@startuml
class Cinema {
name: String
}

class Movielist {
addMovie()
}

class Cinemahall{
name: String
TotalSeats: int
availableSeats()
addCinemahall()

}

class Movie {
titel: String
genre: String
description: String
director: String
length: int
poster: graphic
}

enum Moviestatus {
ANNOUNCED
CURRENT
ARCHIVED
}

enum Type {
2D
3D
}
enum FSKRating {
FSK0
FSK6
FSK12
FSK16
FSK18
}

class adminAccount {
password: String
}


class Screening {
date: date
begin: time
end: time
addScreening()
}

class Seat {
row: char
seat_nr: int
}

enum Seatstatus {
AVAILABLE
RESERVED
BOOKED
}

class Theaterlayout {
diagramm: graphic?
rows: char
columns: int
choseSeat()
checkValidSeat()
}

class Ticket {
price: int
calculatePrice()
}

enum Ticketcategory{
STANDARD
ERMAESSIGT 
KINDER
FAMILIE
}
'Emäßigt ist schüler/studis/senioren

enum Seatcategory {
LOGE_MIT_BEDIENUNG
LOGE
PARKETT
}

class Booking {
checkAge()
checkDsicount()
}
/'checkAge() Hilfsfunktion, die Message erzeugt a la:
"Sie müssen beim Ticket abholen ihre Ausweise vorzeigen usw.
'/

enum BookingType {
TICKETS_RESERVED
TICKETS_PAID
}

class Customer <<abstract>> {
}

class User <<abstract>> {
id: int
firstName: String
lastName: String
email: String
}

class Registered_User{
password: string
}

Cinema --> "1..*"Booking
Cinema -->"1..*" Cinemahall
Cinema "1"<--> "1..*" Screening
Cinemahall -->"1" Theaterlayout
Cinemahall"1"<-->"1..*" Seat
Screening "1..*"<-->"1" Movie
Screening <-->"1" Cinemahall
Cinema -->"1..*"User
Movie -->"1" FSKRating
Movie -->"1" Type
Ticket --> "1" Screening
Ticket --> "1" Seat
Booking --> "1..*"Ticket
Booking --> "1" Screening
Theaterlayout -->"1..*" Seat
Seat -->"1" Seatcategory
Seat -->"1" Seatstatus

Booking -->"1" BookingType
Booking "0...*"<-->"1" Customer
Customer <|-- Guest
Customer <|-- Registered_User
Movielist-->"1..*" Movie
Cinema -->"1"Movielist
Movie--> "1"Moviestatus
User <|-- Customer
User <|-- adminAccount
Ticket-->Ticketcategory








@enduml